[skip ci] remove bumpversion installation and sudo usage

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -32,8 +32,8 @@ commands:
                 echo "A tagged commit, skip..."
                 circleci step halt
               fi
-      - run: sudo chown -R circleci:circleci /usr/local/bin
-      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.7/site-packages
+      - run: chown -R circleci:circleci /usr/local/bin
+      - run: chown -R circleci:circleci /usr/local/lib/python3.7/site-packages || echo "Unable to change ownership for python3.7 site-packages"
 
       # Download and cache dependencies
       - restore_cache:
